// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "2ndpass",
    platforms: [.macOS(.v15), .iOS(.v18)],
    products: [
        .library(name: "MopLocalIdentity", targets: ["MopLocalIdentity"]),
        .library(name: "MopUI", targets: ["MopUI"]),
        .library(name: "MopCore", targets: ["MopCore"]),
        .library(name: "MopAppSupport", targets: ["MopAppSupport"]),
        .library(name: "MopVaultNext", targets: ["MopVaultNext"]),
        .library(name: "MopSync", targets: ["MopSync"]),
        .library(name: "MopKeychain", targets: ["MopKeychain"]),
        .executable(name: "sp", targets: ["MopCLI"]),
        .executable(name: "MopApp", targets: ["MopApp"]),
        .executable(name: "sp-keychain-check", targets: ["MopKeychainCheck"]),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/app-store-server-library-swift.git", exact: "6.0.0"),
        .package(url: "https://github.com/apple/swift-certificates.git", exact: "1.21.0"),
        .package(url: "https://github.com/apple/swift-asn1.git", exact: "1.7.3"),
        .package(url: "https://github.com/weichsel/ZIPFoundation.git", exact: "0.9.20"),
        .package(url: "https://github.com/apple/swift-argument-parser.git", exact: "1.8.2"),
        .package(url: "https://github.com/DeVitoC/zxcvbn-swift.git", revision: "2d0c1137bab12e2c1dc13f167c650256bf60d0b8"),
    ],
    targets: [
        .target(name: "MopSubscriptions", dependencies: ["MopCore", "MopKeychain"]),
        .target(name: "MopSubscriptionVerification", dependencies: ["MopSubscriptions", .product(name: "AppStoreServerLibrary", package: "app-store-server-library-swift", condition: .when(platforms: [.macOS]))], resources: [.copy("Resources")]),
        .testTarget(name: "MopSubscriptionTests", dependencies: ["MopSubscriptions", "MopSubscriptionVerification"]),
        .target(name: "MopOpenSSH", exclude: ["README.md"]),
        .target(name: "MopCredentials", dependencies: ["MopCore", "MopOpenSSH"]),
        .testTarget(name: "MopCredentialsTests", dependencies: ["MopCredentials", "MopCore", "MopLocalIdentity"]),
        .target(name: "MopCore", dependencies: [.product(name: "zxcvbn", package: "zxcvbn-swift")]),
        .target(name: "MopLocalIdentity", dependencies: ["MopCore", "MopAuth", "MopKeychain", .product(name: "X509", package: "swift-certificates"), .product(name: "SwiftASN1", package: "swift-asn1")]),
        .testTarget(name: "MopLocalIdentityTests", dependencies: ["MopLocalIdentity", "MopCore"]),
        .target(name: "MopAppSupport", dependencies: ["MopCredentials", "MopLocalIdentity", "ZIPFoundation", "MopCore", "MopAuth", "MopKeychain", "MopVaultNext", "MopSync"]),
        .target(name: "MopUI", dependencies: ["MopSubscriptions", "MopLocalIdentity", "MopAppSupport", "MopCore", "MopVaultNext"], resources: [.process("Resources")]),
        .executableTarget(name: "MopApp", dependencies: ["MopUI"]),
        .testTarget(name: "MopAppSupportTests", dependencies: ["MopLocalIdentity", "MopAppSupport", "MopCore", "MopVaultNext"]),
        .testTarget(name: "MopAppTests", dependencies: ["MopLocalIdentity", "MopUI", "MopAppSupport", "MopCore"]),
        .target(name: "MopAuth", dependencies: ["MopCore"]),
        .target(name: "MopSync", dependencies: ["MopCore"]),
        .testTarget(name: "MopSyncTests", dependencies: ["MopSync", "MopCore"]),
        .target(name: "MopKeychain", dependencies: ["MopCore", "MopAuth"]),
        .target(name: "MopVaultNext", dependencies: ["MopCredentials", "MopCore", "MopKeychain"]),
        .testTarget(name: "MopVaultNextTests", dependencies: ["MopVaultNext", "MopCore", "MopSync"]),
        .executableTarget(name: "MopCLI", dependencies: ["MopSubscriptions", "MopSubscriptionVerification", "MopLocalIdentity",
            "MopCore", "MopKeychain", "MopAuth", "MopAppSupport", "MopVaultNext",
            .product(name: "ArgumentParser", package: "swift-argument-parser"),
        ]),
        .executableTarget(name: "MopKeychainCheck", dependencies: ["MopCore", "MopKeychain", "MopAuth", "MopVaultNext"]),
        .testTarget(name: "MopCLITests", dependencies: ["MopLocalIdentity", "MopCLI", "MopCore"]),
        .testTarget(name: "MopCoreTests", dependencies: ["MopCore"]),
    ]
)
