import CryptoKit
import Foundation
import LocalAuthentication
import Security
import MopCore

/// Public account membership and hardware device identity are deliberately distinct.
public struct DevicePublicKey: Codable, Equatable, Sendable {
    public let member: UUID
    public let device: UUID
    public let encryption: Data
    public let signing: Data
    public var fingerprint: String { Codec.digest(try! Codec.encode(self)) }

    public init(member: UUID, device: UUID = UUID(), encryption: Data, signing: Data) throws {
        self.member = member; self.device = device; self.encryption = encryption; self.signing = signing
        try validate()
    }
    func validate() throws {
        guard encryption.count == 65, signing.count == 65, encryption != signing else { throw MopError.invalidIdentity }
        _ = try P256.KeyAgreement.PublicKey(x963Representation: encryption)
        _ = try P256.Signing.PublicKey(x963Representation: signing)
    }
    func verifies(_ signature: Data, message: Data) -> Bool {
        guard let key = try? P256.Signing.PublicKey(x963Representation: signing),
              let signature = try? P256.Signing.ECDSASignature(rawRepresentation: signature) else { return false }
        return key.isValidSignature(signature, for: message)
    }
}

/// Operation interface; never exposes a device's private scalar. Implementations
/// are confined to the service's serial operation permit, including close().
public protocol DeviceOperations: AnyObject {
    var identity: DevicePublicKey { get }
    func sign(_ bytes: Data) throws -> Data
    func unwrap(_ envelope: KeyEnvelope, context: Data) throws -> SymmetricKey
    func close()
}

/// Both keys are generated by the Enclave. No software fallback or scalar import.
/// The application must retain no borrowed key handles outside this provider.
public final class EnclaveDevice: DeviceOperations {
    public struct Representation: Codable, Sendable {
        public let identity: DevicePublicKey
        let encryption: Data
        let signing: Data
    }
    public let identity: DevicePublicKey
    private var encryption: SecureEnclave.P256.KeyAgreement.PrivateKey?
    private var signing: SecureEnclave.P256.Signing.PrivateKey?
    private var context: LAContext?

    public init(member: UUID, context: LAContext) throws {
        guard SecureEnclave.isAvailable else { throw MopError.invalidIdentity }
        var error: Unmanaged<CFError>?
        guard let access = SecAccessControlCreateWithFlags(nil, kSecAttrAccessibleWhenUnlockedThisDeviceOnly,
            [.privateKeyUsage, .userPresence], &error) else { throw MopError.authentication }
        let encryption = try SecureEnclave.P256.KeyAgreement.PrivateKey(accessControl: access, authenticationContext: context)
        let signing = try SecureEnclave.P256.Signing.PrivateKey(accessControl: access, authenticationContext: context)
        identity = try DevicePublicKey(member: member, encryption: encryption.publicKey.x963Representation,
                                     signing: signing.publicKey.x963Representation)
        self.encryption = encryption; self.signing = signing; self.context = context
    }

    public init(representation: Representation, context: LAContext) throws {
        guard SecureEnclave.isAvailable else { throw MopError.invalidIdentity }
        try representation.identity.validate()
        let encryption = try SecureEnclave.P256.KeyAgreement.PrivateKey(dataRepresentation: representation.encryption, authenticationContext: context)
        let signing = try SecureEnclave.P256.Signing.PrivateKey(dataRepresentation: representation.signing, authenticationContext: context)
        guard encryption.publicKey.x963Representation == representation.identity.encryption,
              signing.publicKey.x963Representation == representation.identity.signing else { throw MopError.invalidIdentity }
        identity = representation.identity
        self.encryption = encryption; self.signing = signing; self.context = context
    }

    /// Persist in a non-synchronizable, ThisDeviceOnly Data Protection Keychain
    /// item. These opaque bytes are not a portable backup or a plaintext scalar.
    public func representation() throws -> Representation {
        guard let encryption, let signing, context != nil else { throw MopError.authentication }
        return Representation(identity: identity, encryption: encryption.dataRepresentation, signing: signing.dataRepresentation)
    }
    public func sign(_ bytes: Data) throws -> Data {
        guard let signing, context != nil else { throw MopError.authentication }
        return try signing.signature(for: bytes).rawRepresentation
    }
    public func unwrap(_ envelope: KeyEnvelope, context info: Data) throws -> SymmetricKey {
        guard let encryption, context != nil else { throw MopError.authentication }
        return try envelope.open(using: encryption, context: info)
    }
    public func close() {
        // Real hardware probe: invalidating context alone did NOT revoke an
        // existing signing handle. Nil handles are part of this closed boundary.
        let context = self.context
        self.context = nil; encryption = nil; signing = nil
        context?.invalidate()
    }
    // A concurrent Keychain winner can take ownership of the same LAContext.
    func detachContextAndClose() { context = nil; encryption = nil; signing = nil }
    /// Release all key handles while the caller continues to own an authenticated
    /// session context. The caller must invalidate that context on lock/cancel.
    /// No signing or unwrapping is possible through this provider afterward.
    public func releaseHandles() { detachContextAndClose() }
    deinit { close() }
}
